# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CallbackReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, notify_url: NotifyURL=None):  # noqa: E501
        """CallbackReference - a model defined in Swagger

        :param notify_url: The notify_url of this CallbackReference.  # noqa: E501
        :type notify_url: NotifyURL
        """
        self.swagger_types = {
            'notify_url': NotifyURL
        }

        self.attribute_map = {
            'notify_url': 'notifyURL'
        }

        self._notify_url = notify_url

    @classmethod
    def from_dict(cls, dikt) -> 'CallbackReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CallbackReference of this CallbackReference.  # noqa: E501
        :rtype: CallbackReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notify_url(self) -> NotifyURL:
        """Gets the notify_url of this CallbackReference.


        :return: The notify_url of this CallbackReference.
        :rtype: NotifyURL
        """
        return self._notify_url

    @notify_url.setter
    def notify_url(self, notify_url: NotifyURL):
        """Sets the notify_url of this CallbackReference.


        :param notify_url: The notify_url of this CallbackReference.
        :type notify_url: NotifyURL
        """
        if notify_url is None:
            raise ValueError("Invalid value for `notify_url`, must not be `None`")  # noqa: E501

        self._notify_url = notify_url
