# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001NotificationSubscriptionList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_tracking_subscription: List[UserTrackingSubscription]=None, resource_url: ResourceURL=None):  # noqa: E501
        """InlineResponse2001NotificationSubscriptionList - a model defined in Swagger

        :param user_tracking_subscription: The user_tracking_subscription of this InlineResponse2001NotificationSubscriptionList.  # noqa: E501
        :type user_tracking_subscription: List[UserTrackingSubscription]
        :param resource_url: The resource_url of this InlineResponse2001NotificationSubscriptionList.  # noqa: E501
        :type resource_url: ResourceURL
        """
        self.swagger_types = {
            'user_tracking_subscription': List[UserTrackingSubscription],
            'resource_url': ResourceURL
        }

        self.attribute_map = {
            'user_tracking_subscription': 'userTrackingSubscription',
            'resource_url': 'resourceURL'
        }

        self._user_tracking_subscription = user_tracking_subscription
        self._resource_url = resource_url

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001NotificationSubscriptionList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_notificationSubscriptionList of this InlineResponse2001NotificationSubscriptionList.  # noqa: E501
        :rtype: InlineResponse2001NotificationSubscriptionList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_tracking_subscription(self) -> List[UserTrackingSubscription]:
        """Gets the user_tracking_subscription of this InlineResponse2001NotificationSubscriptionList.


        :return: The user_tracking_subscription of this InlineResponse2001NotificationSubscriptionList.
        :rtype: List[UserTrackingSubscription]
        """
        return self._user_tracking_subscription

    @user_tracking_subscription.setter
    def user_tracking_subscription(self, user_tracking_subscription: List[UserTrackingSubscription]):
        """Sets the user_tracking_subscription of this InlineResponse2001NotificationSubscriptionList.


        :param user_tracking_subscription: The user_tracking_subscription of this InlineResponse2001NotificationSubscriptionList.
        :type user_tracking_subscription: List[UserTrackingSubscription]
        """

        self._user_tracking_subscription = user_tracking_subscription

    @property
    def resource_url(self) -> ResourceURL:
        """Gets the resource_url of this InlineResponse2001NotificationSubscriptionList.


        :return: The resource_url of this InlineResponse2001NotificationSubscriptionList.
        :rtype: ResourceURL
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url: ResourceURL):
        """Sets the resource_url of this InlineResponse2001NotificationSubscriptionList.


        :param resource_url: The resource_url of this InlineResponse2001NotificationSubscriptionList.
        :type resource_url: ResourceURL
        """

        self._resource_url = resource_url
