# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002NotificationSubscriptionList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, zonal_traffic_subscription: List[ZoneStatusSubscription]=None, resource_url: ResourceURL=None):  # noqa: E501
        """InlineResponse2002NotificationSubscriptionList - a model defined in Swagger

        :param zonal_traffic_subscription: The zonal_traffic_subscription of this InlineResponse2002NotificationSubscriptionList.  # noqa: E501
        :type zonal_traffic_subscription: List[ZoneStatusSubscription]
        :param resource_url: The resource_url of this InlineResponse2002NotificationSubscriptionList.  # noqa: E501
        :type resource_url: ResourceURL
        """
        self.swagger_types = {
            'zonal_traffic_subscription': List[ZoneStatusSubscription],
            'resource_url': ResourceURL
        }

        self.attribute_map = {
            'zonal_traffic_subscription': 'zonalTrafficSubscription',
            'resource_url': 'resourceURL'
        }

        self._zonal_traffic_subscription = zonal_traffic_subscription
        self._resource_url = resource_url

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002NotificationSubscriptionList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2_notificationSubscriptionList of this InlineResponse2002NotificationSubscriptionList.  # noqa: E501
        :rtype: InlineResponse2002NotificationSubscriptionList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def zonal_traffic_subscription(self) -> List[ZoneStatusSubscription]:
        """Gets the zonal_traffic_subscription of this InlineResponse2002NotificationSubscriptionList.


        :return: The zonal_traffic_subscription of this InlineResponse2002NotificationSubscriptionList.
        :rtype: List[ZoneStatusSubscription]
        """
        return self._zonal_traffic_subscription

    @zonal_traffic_subscription.setter
    def zonal_traffic_subscription(self, zonal_traffic_subscription: List[ZoneStatusSubscription]):
        """Sets the zonal_traffic_subscription of this InlineResponse2002NotificationSubscriptionList.


        :param zonal_traffic_subscription: The zonal_traffic_subscription of this InlineResponse2002NotificationSubscriptionList.
        :type zonal_traffic_subscription: List[ZoneStatusSubscription]
        """

        self._zonal_traffic_subscription = zonal_traffic_subscription

    @property
    def resource_url(self) -> ResourceURL:
        """Gets the resource_url of this InlineResponse2002NotificationSubscriptionList.


        :return: The resource_url of this InlineResponse2002NotificationSubscriptionList.
        :rtype: ResourceURL
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url: ResourceURL):
        """Sets the resource_url of this InlineResponse2002NotificationSubscriptionList.


        :param resource_url: The resource_url of this InlineResponse2002NotificationSubscriptionList.
        :type resource_url: ResourceURL
        """

        self._resource_url = resource_url
