# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, notification_subscription_list: InlineResponse200NotificationSubscriptionList=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param notification_subscription_list: The notification_subscription_list of this InlineResponse200.  # noqa: E501
        :type notification_subscription_list: InlineResponse200NotificationSubscriptionList
        """
        self.swagger_types = {
            'notification_subscription_list': InlineResponse200NotificationSubscriptionList
        }

        self.attribute_map = {
            'notification_subscription_list': 'notificationSubscriptionList'
        }

        self._notification_subscription_list = notification_subscription_list

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_subscription_list(self) -> InlineResponse200NotificationSubscriptionList:
        """Gets the notification_subscription_list of this InlineResponse200.


        :return: The notification_subscription_list of this InlineResponse200.
        :rtype: InlineResponse200NotificationSubscriptionList
        """
        return self._notification_subscription_list

    @notification_subscription_list.setter
    def notification_subscription_list(self, notification_subscription_list: InlineResponse200NotificationSubscriptionList):
        """Sets the notification_subscription_list of this InlineResponse200.


        :param notification_subscription_list: The notification_subscription_list of this InlineResponse200.
        :type notification_subscription_list: InlineResponse200NotificationSubscriptionList
        """

        self._notification_subscription_list = notification_subscription_list
