# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LocationInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, latitude: float=None, longitude: float=None, altitude: float=None, accuracy: int=None):  # noqa: E501
        """LocationInfo - a model defined in Swagger

        :param latitude: The latitude of this LocationInfo.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this LocationInfo.  # noqa: E501
        :type longitude: float
        :param altitude: The altitude of this LocationInfo.  # noqa: E501
        :type altitude: float
        :param accuracy: The accuracy of this LocationInfo.  # noqa: E501
        :type accuracy: int
        """
        self.swagger_types = {
            'latitude': float,
            'longitude': float,
            'altitude': float,
            'accuracy': int
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude',
            'altitude': 'altitude',
            'accuracy': 'accuracy'
        }

        self._latitude = latitude
        self._longitude = longitude
        self._altitude = altitude
        self._accuracy = accuracy

    @classmethod
    def from_dict(cls, dikt) -> 'LocationInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LocationInfo of this LocationInfo.  # noqa: E501
        :rtype: LocationInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> float:
        """Gets the latitude of this LocationInfo.


        :return: The latitude of this LocationInfo.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this LocationInfo.


        :param latitude: The latitude of this LocationInfo.
        :type latitude: float
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this LocationInfo.


        :return: The longitude of this LocationInfo.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this LocationInfo.


        :param longitude: The longitude of this LocationInfo.
        :type longitude: float
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def altitude(self) -> float:
        """Gets the altitude of this LocationInfo.


        :return: The altitude of this LocationInfo.
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude: float):
        """Sets the altitude of this LocationInfo.


        :param altitude: The altitude of this LocationInfo.
        :type altitude: float
        """

        self._altitude = altitude

    @property
    def accuracy(self) -> int:
        """Gets the accuracy of this LocationInfo.


        :return: The accuracy of this LocationInfo.
        :rtype: int
        """
        return self._accuracy

    @accuracy.setter
    def accuracy(self, accuracy: int):
        """Sets the accuracy of this LocationInfo.


        :param accuracy: The accuracy of this LocationInfo.
        :type accuracy: int
        """
        if accuracy is None:
            raise ValueError("Invalid value for `accuracy`, must not be `None`")  # noqa: E501

        self._accuracy = accuracy
