# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user: List[UserInfo]=None, resource_url: ResourceURL=None):  # noqa: E501
        """UserList - a model defined in Swagger

        :param user: The user of this UserList.  # noqa: E501
        :type user: List[UserInfo]
        :param resource_url: The resource_url of this UserList.  # noqa: E501
        :type resource_url: ResourceURL
        """
        self.swagger_types = {
            'user': List[UserInfo],
            'resource_url': ResourceURL
        }

        self.attribute_map = {
            'user': 'user',
            'resource_url': 'resourceURL'
        }

        self._user = user
        self._resource_url = resource_url

    @classmethod
    def from_dict(cls, dikt) -> 'UserList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserList of this UserList.  # noqa: E501
        :rtype: UserList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> List[UserInfo]:
        """Gets the user of this UserList.

        Collection of the zone information list.  # noqa: E501

        :return: The user of this UserList.
        :rtype: List[UserInfo]
        """
        return self._user

    @user.setter
    def user(self, user: List[UserInfo]):
        """Sets the user of this UserList.

        Collection of the zone information list.  # noqa: E501

        :param user: The user of this UserList.
        :type user: List[UserInfo]
        """

        self._user = user

    @property
    def resource_url(self) -> ResourceURL:
        """Gets the resource_url of this UserList.


        :return: The resource_url of this UserList.
        :rtype: ResourceURL
        """
        return self._resource_url

    @resource_url.setter
    def resource_url(self, resource_url: ResourceURL):
        """Sets the resource_url of this UserList.


        :param resource_url: The resource_url of this UserList.
        :type resource_url: ResourceURL
        """
        if resource_url is None:
            raise ValueError("Invalid value for `resource_url`, must not be `None`")  # noqa: E501

        self._resource_url = resource_url
